name: bubbles
description: A Collection of Bubble widgets
version: 0.0.2
publish_to: "none"
homepage: https://github.com/RagehAz/bubbles.git
# --------------------------------------------------------------------------------
environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # -----------------
  super_text_field:
    git:
      url: https://github.com/RagehAz/super_text_field.git
  scale:
    git:
      url: https://github.com/RagehAz/scale.git
  super_box:
    git:
      url: https://github.com/RagehAz/super_box.git
  super_text:
    git:
      url: https://github.com/RagehAz/super_text.git
# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
# --------------------------------------------------------------------------------
flutter:
